### PR TITLE
Chore/random bug fixes

### LINKED ISSUE #26: Header is different in home and courses
For consistency, header should not change in different pages.
Besides, there is a button dashboard that does nothing goes nowhere, and in the other pages it show me my name (which I think that is better).

Home:
image

Rest of the app:
image

### PR DESCRIPTION
**Pull request by MagnusHJensen**
closes: #26 

This PR fixes some random issues I fell over, while looking for other bugs.

It also includes the UserId as a property to the teams webhook

Also makes the LinkRepo module user friendly:
image

### CODE REVIEW

File: app/Http/Controllers/Api/UserController.php [hunk 1]
```diff
@@ -43,7 +42,7 @@ public function repositories() : \Illuminate\Support\Collection
             ->selectName()
             ->selectCreatedAt()
             ->selectNamespace()->selectName()->selectFullName();
-        $token = App::environment(['local']) ? env('GITLAB_ACCESS_TOKEN') : auth()->user()->access_token;
```
Comment (mcamp) [inline app/Http/Controllers/Api/UserController.php:46]: why we do not use user access token?

Comment (MagnusHJensen) [reply app/Http/Controllers/Api/UserController.php:46]: We don't want it since there is no refresh flow in place.

So if you are logged in for more than 1 hour, the access_token generated on login, will expire making the search fail.

This also leads to another problem, since the "Bot account" is the one that creates and forks projects, but the search was based on your own, you could find more repositories than the bot had access to making it fail to create the assignment, since it does not have access to fork a repo it is not a member of.

**Review by mcamp — APPROVED** [review]
